### ISSUE TITLE
InfografiaLibrerias

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/infografia-de-las-librerias-Aricel117#2]
[Infografia Librerias.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Aricel117/files/6355312/Infografia.Librerias.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo compañero, buen diseño y las imágenes contrastan bien con el fondo. Solamente te falto citar las fuentes de las imágenes, ahí en fuera muy buen trabajo.  
Porcentaje obtenido: 18% de 20% posibles

**Comment by josealfredo79** [comment]
Bien hecho y revisado
